# Generated by Django 6.0.3 on 2026-03-04 04:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehicles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RentalPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('hourly_rate', models.DecimalField(decimal_places=2, help_text='Company pays owner this rate per hour.', max_digits=10)),
                ('per_km_rate', models.DecimalField(decimal_places=2, help_text='Company pays owner this rate per km driven.', max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Rental Policies',
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('purpose', models.TextField(help_text='Why is this vehicle needed for company business?')),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('approved', 'Approved'), ('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='requested', max_length=20)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='vehicles.vehicle')),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='rentals.rentalpolicy')),
            ],
        ),
        migrations.CreateModel(
            name='TripLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_odometer', models.IntegerField()),
                ('end_odometer', models.IntegerField()),
                ('driver_feedback', models.TextField(blank=True, help_text='Any issues with the car?')),
                ('owner_feedback', models.TextField(blank=True, help_text='Was the car returned in good condition?')),
                ('logged_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trip_log', to='rentals.booking')),
            ],
        ),
    ]
